[project]
name = "uv-repro"
version = "0.1.0"
description = "uv bug minimal reproducible example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dep1",
]

[tool.uv.workspace]
members = [
    "packages/*",
]

[tool.uv.sources]
dep1 = { workspace = true }
